### ISSUE TITLE
release on pypi?

### ISSUE THREAD

**Issue by mcclurem** [dw/alembic-autogenerate-enums#4]
Hey, this repo seems to solve an irritating problem. Any chance you're planning to do a release on pypi so people don't have to keep downloading this repo and running setup.py? alternatively, any chance you'd try to merge upstream into main alembic?

**Comment by dw** [comment]
Hi,

This will never make it into upstream Alembic, but I'll happily throw it up on pypi this evening.

Will update ticket when done.

Thanks,


David

**Comment by dw** [comment]
https://pypi.python.org/pypi/alembic_autogenerate_enums/0.0.2
